/* School account UI and protected lesson bootstrap. No lesson executes before Auth. */
window.PYAccount=(()=>{'use strict';
 const C=PyCloud,engineURL=new URL('engine.js',document.currentScript.src),isLesson=Boolean(window.PY_LESSON_KEY);
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const $=s=>document.querySelector(s);let started=false,owner=null,mode='login';
 function err(e){const m=String(e.message||e);if(/Invalid login credentials/i.test(m))return 'Mã học sinh/email hoặc mật khẩu chưa đúng.';if(/rate/i.test(m))return 'Thao tác quá nhanh. Chờ một chút rồi thử lại.';if(/operation_failed/.test(m))return 'Chưa thực hiện được. Mã có thể đã có tài khoản; hãy đăng nhập hoặc liên hệ giáo viên.';return m}
 function dialog(html){let d=$('#school-dialog');if(!d){d=document.createElement('dialog');d.id='school-dialog';d.className='modal';document.body.append(d)}d.innerHTML='<div class="modal-card"><button type="button" class="close-x" data-school-close aria-label="Đóng">×</button>'+html+'</div>';d.querySelector('[data-school-close]').onclick=()=>d.close();if(!d.open)d.showModal();return d}
 function auth(nextMode='login'){
  mode=nextMode;const reg=mode==='register';
  const d=dialog(`<div class="eyebrow">TÀI KHOẢN LSTS · DÙNG CHUNG PYTHON VÀ SQL</div><h2>${reg?'Đăng ký học sinh':'Đăng nhập để học'}</h2><p>Dùng tài khoản MSHS đã có ở SQL. Chỉ đăng ký một lần cho hai khóa.</p><div class="row-btns"><button type="button" data-login>Đăng nhập</button><button type="button" data-register>Đăng ký</button></div><form id="school-auth"><label class="field">${reg?'Mã học sinh (7 chữ số)':'Mã học sinh hoặc email giáo viên'}<input name="identity" required autocomplete="username" ${reg?'pattern="[0-9]{7}" maxlength="7" inputmode="numeric"':''}></label>${reg?'<label class="field">Họ và tên<input name="name" maxlength="100" required autocomplete="name"></label><label class="field">Lớp học thuật<input name="class" maxlength="30" required placeholder="Ví dụ: 10A2"></label><label class="field">Family (nếu có)<input name="family" maxlength="60"></label><p class="muted">Email tự tạo: MSHS@lsts.edu.vn.</p>':''}<label class="field">Mật khẩu<input name="password" type="password" minlength="10" maxlength="128" required autocomplete="${reg?'new-password':'current-password'}"></label>${reg?'<label class="field">Nhập lại mật khẩu<input name="confirm" type="password" minlength="10" required autocomplete="new-password"></label>':''}<button class="btn primary" type="submit">${reg?'Đăng ký':'Đăng nhập'}</button><p id="school-error" role="alert"></p></form><p class="muted">Không cần xác nhận email. Quên mật khẩu: nhờ giáo viên xác minh và hỗ trợ; mã học sinh không đủ để tự đặt lại mật khẩu.</p>`);
  d.querySelector('[data-login]').onclick=()=>auth('login');d.querySelector('[data-register]').onclick=()=>auth('register');
  d.querySelector('form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),b=e.target.querySelector('button');b.disabled=true;$('#school-error').textContent='';try{const id=fd.get('identity').trim().toLowerCase(),pw=fd.get('password');if(reg){if(pw!==fd.get('confirm'))throw Error('Hai mật khẩu chưa giống nhau.');await C.signUp(id,fd.get('name').trim(),fd.get('class').trim(),fd.get('family').trim(),pw)}else{const email=/^\d{7}$/.test(id)?id+'@lsts.edu.vn':id;if(!/^[a-z0-9._+-]+@lsts\.edu\.vn$/.test(email))throw Error('Dùng MSHS 7 chữ số hoặc email trường.');await C.signIn(email,pw)}d.close();await enter()}catch(e){$('#school-error').textContent=err(e)}finally{b.disabled=false}};
 }
 function student(){return {name:C.profile.display_name,className:C.profile.class_label,studentCode:C.profile.student_code,userId:C.user.id}}
 function profile(){
  if(!C.allowed())return auth();const p=C.profile;
  const d=dialog(`<div class="eyebrow">HỒ SƠ DÙNG CHUNG CÁC KHÓA</div><h2>${esc(p.display_name)}</h2><p>${esc(C.user.email)} · ${esc(p.student_code||'Giáo viên')}</p><form id="school-profile"><label class="field">Họ và tên<input name="name" value="${esc(p.display_name)}" maxlength="100" required></label><label class="field">Lớp học thuật<input name="class" value="${esc(p.class_label)}" maxlength="30" ${p.student_code?'required':''}></label><label class="field">Family<input name="family" value="${esc(p.family)}" maxlength="60"></label><button class="btn primary">Lưu hồ sơ</button><p data-profile-msg role="status"></p></form><details><summary>Đổi mật khẩu</summary><form id="school-password"><label class="field">Mật khẩu hiện tại<input name="current" type="password" autocomplete="current-password" required></label><label class="field">Mật khẩu mới<input name="new" type="password" minlength="10" maxlength="128" autocomplete="new-password" required></label><label class="field">Nhập lại mật khẩu mới<input name="confirm" type="password" minlength="10" autocomplete="new-password" required></label><button class="btn">Đổi mật khẩu</button><p data-password-msg role="status"></p></form></details><p class="muted">Đổi tên/lớp/family không đổi MSHS hoặc bài làm. Hồ sơ mới được dùng ở Python và SQL.</p><div class="row-btns"><button class="btn" data-import>Chuyển bài làm cũ từ máy này</button><button class="btn" data-download>Tải bản sao Python</button><button class="btn" data-logout>Đăng xuất</button></div>`);
  d.querySelector('#school-profile').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await C.updateProfile({display_name:f.get('name').trim(),class_label:f.get('class').trim(),family:f.get('family').trim()});d.querySelector('[data-profile-msg]').textContent='Đã lưu hồ sơ. Bài làm vẫn giữ nguyên.'}catch(e){d.querySelector('[data-profile-msg]').textContent=err(e)}};
  d.querySelector('#school-password').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{if(f.get('new')!==f.get('confirm'))throw Error('Hai mật khẩu mới chưa giống nhau.');await C.password(f.get('current'),f.get('new'));e.target.reset();d.querySelector('[data-password-msg]').textContent='Đã đổi mật khẩu.'}catch(e){d.querySelector('[data-password-msg]').textContent=err(e)}};
  d.querySelector('[data-logout]').onclick=async()=>{try{await C.signOut()}catch(e){d.querySelector('[data-profile-msg]').textContent=err(e)}};
  d.querySelector('[data-import]').onclick=legacy;
  d.querySelector('[data-download]').onclick=()=>{const data={course:'python-10',student:student(),savedAt:new Date().toISOString(),lessons:Object.fromEntries(C.lessons.map(l=>[l.lesson_key,C.state(l.lesson_key)]))};const a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.href=u;a.download='python10-ban-sao.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),5000)};
 }
 function legacy(){
  const groups=new Map();for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i),m=/^py10:(bai0[1-9]):([0-9A-F]{8})$/.exec(k||'');if(!m)continue;try{const s=JSON.parse(localStorage.getItem(k));if(!s?.student?.name||!s?.student?.className)continue;if(!groups.has(m[2]))groups.set(m[2],{student:s.student,rows:[]});groups.get(m[2]).rows.push([m[1],s])}catch{}}
  const entries=[...groups.values()],d=dialog(`<h2>Chuyển bài làm cũ</h2><p>Chọn đúng bài làm của mình trên thiết bị này. Tiến độ cũ là dữ liệu tự học do máy lưu, chưa được giáo viên xác minh. Bài đã có kết quả/nháp trên tài khoản sẽ được giữ.</p>${entries.length?`<form id="legacy-import"><label class="field">Hồ sơ cũ<select name="group">${entries.map((g,i)=>`<option value="${i}">${esc(g.student.name)} · ${esc(g.student.className)} · ${g.rows.length} bài</option>`).join('')}</select></label><label><input type="checkbox" required> Tôi xác nhận đây là bài làm của mình.</label><p><button class="btn primary">Chuyển vào tài khoản</button></p><p data-import-msg role="status"></p></form>`:'<p>Không có bài làm cũ trên trình duyệt này. Bài cũ trên máy khác chưa thể tự tìm qua mạng.</p>'}`);
  d.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();const g=entries[Number(new FormData(e.target).get('group'))];let imported=0,skipped=0;for(const [id,old]of g.rows){const remote=C.state(id),meaningful=s=>Boolean(s.completedAt||Object.values(s.passed||{}).some(Boolean)||Object.keys(s.drafts||{}).length||Object.keys(s.inputs||{}).length);if(meaningful(remote)){skipped++;continue}const s={...old,student:student(),importedAt:new Date().toISOString(),importSource:'local-self-reported',completed:Boolean(old.completedAt)};if(C.save(id,s))imported++}await C.flush();d.querySelector('[data-import-msg]').textContent=`Đã chuyển ${imported} bài; giữ nguyên ${skipped} bài có dữ liệu trên tài khoản. ${Object.keys(C.pending).length?'Có bản đang chờ lưu hoặc cần đối chiếu.':''}`;window.PY_ENGINE?.remoteState?.()});
 }
 async function staff(){
  if(!C.allowed()||C.role==='student')return;const ownerId=C.user.id,d=dialog('<h2>Quản lí khóa Python</h2><p>Đang tải…</p>');
  try{const data=await C.dashboard();if(!C.allowed()||C.user.id!==ownerId)return;
   d.querySelector('.modal-card').innerHTML=`<button type="button" class="close-x" data-school-close aria-label="Đóng">×</button><h2>Quản lí khóa Python · 2026–2027</h2><p>Lọc theo lớp học thuật để xem nhanh. Tạo lớp bằng mã và giao bài theo lịch chưa được triển khai.</p><label class="field">Lọc tên/MSHS/lớp<input id="teacher-filter" type="search"></label><div class="table-wrap"><table><thead><tr><th>MSHS</th><th>Họ tên</th><th>Lớp học thuật</th><th>Hoàn thành</th><th>Bài làm</th></tr></thead><tbody>${data.students.map(s=>`<tr data-student-row><td>${esc(s.student_code)}</td><td>${esc(s.display_name)}</td><td>${esc(s.class_label)}</td><td>${Number(s.completed)||0}/9</td><td><button class="btn" data-detail="${esc(s.user_id)}">Xem</button><button class="btn" data-reset="${esc(s.user_id)}">Mật khẩu tạm</button></td></tr>`).join('')}</tbody></table></div><h3>Giáo viên</h3><ul>${data.teachers.map(t=>`<li>${esc(t.display_name)} · ${esc(t.email)}</li>`).join('')||'<li>Chưa thêm giáo viên.</li>'}</ul>${C.role==='admin'?'<details><summary>Thêm giáo viên vào Python</summary><form id="add-teacher"><label class="field">Email trường<input name="email" type="email" required></label><label class="field">Họ tên<input name="name" maxlength="100" required></label><label class="field">Mật khẩu tạm nếu là tài khoản mới<input name="password" type="password" minlength="10" autocomplete="new-password"></label><button class="btn primary">Thêm giáo viên</button><p data-staff-msg role="status"></p></form></details>':''}`;
   d.querySelector('[data-school-close]').onclick=()=>d.close();d.querySelector('#teacher-filter').oninput=e=>d.querySelectorAll('[data-student-row]').forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(e.target.value.toLowerCase()));
   d.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail));
   d.querySelectorAll('[data-reset]').forEach(b=>b.onclick=()=>{const uid=b.dataset.reset;const r=dialog('<h2>Hỗ trợ mật khẩu</h2><p>Xác minh danh tính học sinh trước khi đặt mật khẩu tạm.</p><form id="reset-password"><label class="field">Mật khẩu tạm<input name="password" type="password" minlength="10" maxlength="128" required autocomplete="new-password"></label><button class="btn primary">Đặt mật khẩu tạm</button><p data-msg role="status"></p></form>');r.querySelector('form').onsubmit=async e=>{e.preventDefault();try{await C.admin({action:'reset_password',userId:uid,password:new FormData(e.target).get('password')});e.target.reset();r.querySelector('[data-msg]').textContent='Đã đặt mật khẩu tạm; phiên làm mới đã thu hồi.'}catch(e){r.querySelector('[data-msg]').textContent=err(e)}}});
   d.querySelector('#add-teacher')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{await C.admin({action:'add_teacher',email:f.get('email'),name:f.get('name'),password:f.get('password')});e.target.reset();d.querySelector('[data-staff-msg]').textContent='Đã thêm giáo viên vào khóa Python.'}catch(e){d.querySelector('[data-staff-msg]').textContent=err(e)}});
  }catch(e){d.querySelector('.modal-card').textContent=err(e)}
 }
 async function detail(uid,id='bai01'){
  try{const data=await C.detail(uid,id);if(!C.allowed()||C.role==='student')return;const p=data.progress[0]?.state||{},d=dialog(`<h2>${esc(data.profile.display_name)}</h2><label class="field">Bài<select id="detail-lesson">${C.lessons.map(l=>`<option value="${esc(l.lesson_key)}" ${l.lesson_key===id?'selected':''}>${l.position}. ${esc(l.title)}</option>`).join('')}</select></label><p>${p.completed?'Đã hoàn thành tự học':'Đang học'} · ${Object.values(p.passed||{}).filter(Boolean).length} nhiệm vụ đạt · ${p.navigationMode==='self-study'?'Tự học / học bù':'Theo lớp'}</p>${Object.entries(p.drafts||{}).map(([key,code])=>`<details><summary>${esc(key)} · ${Number(p.attempts?.[key])||0} lần kiểm tra</summary><pre>${esc(code)}</pre></details>`).join('')||'<p>Chưa có nháp Python.</p>'}<p class="muted">Tiến độ và huy hiệu là kết quả tự học; giáo viên đối chiếu minh chứng để đánh giá chính thức.</p>`);d.querySelector('#detail-lesson').onchange=e=>detail(uid,e.target.value)}catch(e){dialog('<p>'+esc(err(e))+'</p>')}
 }
 function controls(){
  if(!$('#school-controls')){const wrap=document.createElement('div');wrap.id='school-controls';wrap.className='school-controls';wrap.innerHTML='<span id="school-sync" role="status"></span><button class="btn" id="school-staff" hidden>Quản lí khóa</button><button class="btn" id="school-account">Đăng nhập</button>';($('header.topbar')||document.body).append(wrap);$('#school-account').onclick=()=>C.allowed()?profile():auth();$('#school-staff').onclick=staff}
  $('#school-account').textContent=C.allowed()?C.profile.display_name:'Đăng nhập';$('#school-staff').hidden=!C.allowed()||C.role==='student';$('#school-sync').textContent=C.status||'';
  const lid=isLesson?C.lessonId(PY_LESSON_KEY):null;let box=$('#school-conflict');if(lid&&C.conflicts[lid]){if(!box){box=document.createElement('section');box.id='school-conflict';box.className='cloud-conflict';box.innerHTML='<p>Bài làm đã đổi ở máy khác. Tải bản sao trong Hồ sơ trước khi chọn nếu cần giữ cả hai.</p><button class="btn" data-local>Giữ nháp máy này</button><button class="btn" data-remote>Dùng bản trên tài khoản</button>';document.body.prepend(box);box.querySelector('[data-local]').onclick=()=>C.resolve(PY_LESSON_KEY,true);box.querySelector('[data-remote]').onclick=()=>C.resolve(PY_LESSON_KEY,false)}}else box?.remove();
  if(!isLesson&&$('#me')){const count=C.lessons.filter(l=>C.state(l.lesson_key).completed).length;$('#me').textContent=C.allowed()?`${C.profile.display_name} · ${C.profile.class_label} · đã hoàn thành ${count}/9 bài`:'Đăng ký / đăng nhập để vào học. Tài khoản dùng chung Python và SQL.';document.querySelectorAll('.card[href]').forEach(a=>{a.querySelector('.badge')?.remove();const id=a.getAttribute('href').split('/')[0],s=C.state(id);if(s.completed){const b=document.createElement('span');b.className='badge '+(s.badge||'silver');b.textContent='✓';a.append(b)}})}
 }
 async function enter(){
  controls();if(!isLesson||started||!C.allowed())return;const payload=C.content(PY_LESSON_KEY);if(!payload?.source)throw Error('Chưa có học liệu bài này.');const uid=C.user.id;
  const s=document.createElement('script');s.textContent=payload.source;document.head.append(s);s.remove();if(!C.allowed()||C.user.id!==uid){delete window.LESSON;return}
  window.LESSON.media=payload.media;started=true;owner=uid;
  const script=document.createElement('script');script.src=engineURL.href+'?v='+window.PY_ENGINE_VERSION;await new Promise((resolve,reject)=>{script.onload=resolve;script.onerror=()=>reject(Error('Chưa tải được giao diện. Kiểm tra mạng rồi tải lại.'));document.head.append(script)});controls();
 }
 window.addEventListener('py-cloud-change',()=>{if(started&&(!C.user||C.user.id!==owner)){window.PY_ENGINE?.dispose?.();delete window.LESSON;window.KIT.examples.length=0;document.body.innerHTML='<main class="hub"><h1>Đã đăng xuất</h1><p>Nội dung bài đã đóng.</p></main>';started=false;location.reload();return}controls()});
 async function boot(){try{await C.init();controls();await enter();if(isLesson&&!C.allowed())auth()}catch(e){controls();const p=document.createElement('p');p.className='cloud-error';p.textContent=err(e);document.body.append(p)}}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
 return {auth,profile,staff,student,controls,enter};
})();
